#index:
#    path: /
#    controller: App\Controller\DefaultController::index

tasks:
  path: /
  controller: App\Controller\TaskController::index

# Rutas de usuario
register:
  path: /registro
  controller: App\Controller\UserController::userRegister
login:
  path: /login
  controller: App\Controller\UserController::userLogin
logout:
  path: /logout


  # Rutas de tareas
detail_task:
  path: /tarea/{id}
  controller: App\Controller\TaskController::detail
create_task:
  path: /tarea/crear
  controller: App\Controller\TaskController::create