#index:
#    path: /
#    controller: App\Controller\DefaultController::index

tasks:
  path: /tasks
  controller: App\Controller\TaskController::index
register:
  path: /registro
  controller: App\Controller\UserController::userRegister

login:
  path: /login
  controller: App\Controller\UserController::userLogin

logout:
  path: /logout