#index:
#    path: /
#    controller: App\Controller\DefaultController::index

task:
  path: /tasks
  controller: App\Controller\TaskController::index
register:
  path: /registro
  controller: App\Controller\UserController::userRegister